import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(new URL('..', import.meta.url).pathname)

function read(path) {
 return fs.readFileSync(path, 'utf8')
}

test('EntityListTable exposes simplified typed props contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/EntityListTable.vue'))
 assert.match(source, /interface EntityListTableProps/)
 assert.match(source, /rowKey: string/)
 assert.match(source, /columns\?: InputColumn\[\]/)
 assert.match(source, /items\?: Record<string, unknown>\[\]/)
 assert.doesNotMatch(source, /mobileItems\?: Record<string, unknown>\[\]/)
 assert.doesNotMatch(source, /tableKey\?: string/)
 assert.doesNotMatch(source, /columnLabels\?: Record<string, string>/)
})

test('PermissionGuard exposes granted prop', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/PermissionGuard.vue'))
 assert.match(source, /granted\?: boolean/)
 assert.match(source, /slot name="fallback"/)
})

test('MainPage exposes concrete shell and global agent contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/pages/MainPage.vue'))
 assert.match(source, /interface MainPageProps/)
 assert.match(source, /moreLabel\?: string/)
 assert.match(source, /agentPlaceholder\?: string/)
 assert.match(source, /agentSessionsOpen\?: boolean/)
 assert.match(source, /profileDialog\?: MainPageProfileDialog/)
 assert.match(source, /passwordDialog\?: MainPagePasswordDialog/)
 assert.match(source, /slot name="sidebar"/)
 assert.match(source, /slot name="toolbar"/)
 assert.match(source, /slot name="alerts"/)
 assert.match(source, /slot name="agent-sessions"/)
 assert.match(source, /slot name="agent-output"/)
 assert.match(source, /submit-agent/)
 assert.match(source, /submit-profile/)
 assert.match(source, /submit-password/)
 assert.match(source, /update:agentSessionsOpen/)
 assert.match(source, /import LocaleSwitcher from '\.\.\/controls\/LocaleSwitcher\.vue'/)
 assert.match(source, /import ThemeSwitcher from '\.\.\/controls\/ThemeSwitcher\.vue'/)
 assert.match(source, /<LocaleSwitcher/)
 assert.match(source, /<ThemeSwitcher/)
 assert.match(source, /import SemanticIcon from '\.\.\/controls\/SemanticIcon\.vue'/)
 assert.match(source, /<SemanticIcon name="menu"/)
 assert.match(source, /<SemanticIcon name="more"/)
 assert.match(source, /<SemanticIcon name="send"/)
 assert.match(source, /mobileMenuLabel: '切换导航'/)
 assert.match(source, /orgLabel: '组织'/)
 assert.match(source, /localeLabel: '语言'/)
 assert.match(source, /themeLabel: '主题'/)
 assert.match(source, /logoutLabel: '退出登录'/)
 assert.match(source, /profileDialog: \(\) => \(\{/)
 assert.match(source, /passwordDialog: \(\) => \(\{/)
 assert.doesNotMatch(source, /profileLabel\?: string/)
 assert.doesNotMatch(source, /passwordLabel\?: string/)
 assert.doesNotMatch(source, /saveLabel\?: string/)
})

test('SemanticIcon exposes unified semantic token contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/SemanticIcon.vue'))
 assert.match(source, /interface SemanticIconProps/)
 assert.match(source, /name\?: string/)
 assert.match(source, /fallback\?: string/)
 assert.match(source, /label\?: string/)
 assert.match(source, /size\?: 'sm' \| 'md' \| 'lg'/)
 assert.match(source, /resolveSemanticIcon/)
})

test('DemoSidebarNav wires sidebar rendering to runtime menu builder and semantic icons', () => {
 const source = read(path.join(repoRoot, 'apps/demo-app/src/components/DemoSidebarNav.vue'))
 assert.match(source, /buildSidebarMenuTree/)
 assert.match(source, /SemanticIcon/)
 assert.match(source, /RouterLink/)
 assert.match(source, /defineOptions\(\{ name: 'DemoSidebarNav' \}\)/)
})

test('AuthPage exposes stronger auth-shell props and slots contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/pages/AuthPage.vue'))
 assert.match(source, /interface AuthPageProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /maxWidth\?: string/)
 assert.match(source, /layout\?: 'centered' \| 'split'/)
 assert.match(source, /panelWidth\?: string/)
 assert.match(source, /heroTitle\?: string/)
 assert.match(source, /heroSubtitle\?: string/)
 assert.match(source, /showLocaleSwitcher\?: boolean/)
 assert.match(source, /showThemeSwitcher\?: boolean/)
 assert.match(source, /locale\?: string/)
 assert.match(source, /theme\?: string/)
 assert.match(source, /localeOptions\?: PageOption\[\]/)
 assert.match(source, /themeOptions\?: PageOption\[\]/)
 assert.match(source, /footerText\?: string/)
 assert.match(source, /supportText\?: string/)
 assert.match(source, /backgroundVariant\?: 'soft' \| 'strong' \| 'plain'/)
 assert.match(source, /slot name="brand"/)
 assert.match(source, /slot name="hero"/)
 assert.match(source, /slot name="header"/)
 assert.match(source, /slot name="alerts"/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="locale-action"/)
 assert.match(source, /slot name="theme-action"/)
 assert.match(source, /slot name="footer"/)
 assert.match(source, /import LocaleSwitcher from '\.\.\/controls\/LocaleSwitcher\.vue'/)
 assert.match(source, /import ThemeSwitcher from '\.\.\/controls\/ThemeSwitcher\.vue'/)
 assert.match(source, /update:locale/)
 assert.match(source, /update:theme/)
 assert.doesNotMatch(source, /centered\?: boolean/)
})

test('LocaleSwitcher and ThemeSwitcher expose standard switch contracts', () => {
 const localeSource = read(path.join(repoRoot, 'packages/vue/src/components/controls/LocaleSwitcher.vue'))
 const themeSource = read(path.join(repoRoot, 'packages/vue/src/components/controls/ThemeSwitcher.vue'))
 assert.match(localeSource, /interface LocaleSwitcherProps/)
 assert.match(localeSource, /modelValue\?: string/)
 assert.match(localeSource, /options\?: LocaleOption\[\]/)
 assert.match(localeSource, /update:modelValue/)
 assert.match(localeSource, /SemanticIcon/)
 assert.match(themeSource, /interface ThemeSwitcherProps/)
 assert.match(themeSource, /modelValue\?: string/)
 assert.match(themeSource, /options\?: ThemeOption\[\]/)
 assert.match(themeSource, /update:modelValue/)
 assert.match(themeSource, /SemanticIcon/)
})

test('AppButton exposes foundational action props and slots contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/AppButton.vue'))
 assert.match(source, /interface AppButtonProps/)
 assert.match(source, /size\?: 'sm' \| 'md' \| 'lg'/)
 assert.match(source, /loading\?: boolean/)
 assert.match(source, /block\?: boolean/)
 assert.match(source, /slot name="leading"/)
 assert.match(source, /slot name="trailing"/)
})

test('AppInput exposes foundational form-control props and slots contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/AppInput.vue'))
 assert.match(source, /interface AppInputProps/)
 assert.match(source, /disabled\?: boolean/)
 assert.match(source, /readonly\?: boolean/)
 assert.match(source, /invalid\?: boolean/)
 assert.match(source, /slot name="leading"/)
 assert.match(source, /slot name="trailing"/)
})

test('AppSelect exposes foundational select props contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/AppSelect.vue'))
 assert.match(source, /interface AppSelectProps/)
 assert.match(source, /modelValue\?: string/)
 assert.match(source, /placeholder\?: string/)
 assert.match(source, /disabled\?: boolean/)
 assert.match(source, /optionLabelKey\?: string/)
 assert.match(source, /optionValueKey\?: string/)
 assert.match(source, /optionDisabledKey\?: string/)
 assert.match(source, /update:modelValue', value: string/)
 assert.doesNotMatch(source, /type OptionValue = string \| number/)
})

test('AppField exposes foundational label-help-error contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/AppField.vue'))
 assert.match(source, /interface AppFieldProps/)
 assert.match(source, /hint\?: string/)
 assert.match(source, /error\?: string/)
 assert.match(source, /required\?: boolean/)
})

test('AppPanel exposes foundational panel header actions contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/controls/AppPanel.vue'))
 assert.match(source, /interface AppPanelProps/)
 assert.match(source, /padded\?: boolean/)
 assert.match(source, /borderless\?: boolean/)
 assert.match(source, /slot name="actions"/)
})

test('PagePanel exposes header actions slot contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/PagePanel.vue'))
 assert.match(source, /interface PagePanelProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /slot name="actions"/)
})

test('QueryToolbar exposes enriched header and submit contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/QueryToolbar.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /slot name="headerActions"/)
 assert.match(source, /slot name="after"/)
 assert.match(source, /'submit'/)
})

test('EntityListTable exposes simplified column settings and pagination contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/EntityListTable.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /labels\?: EntityListTableLabels/)
 assert.match(source, /showPagination\?: boolean/)
 assert.match(source, /inferredColumns/)
 assert.match(source, /storageKey = computed/)
 assert.match(source, /getCurrentInstance/)
 assert.match(source, /resolveLabel/)
 assert.match(source, /resolvedLabels = computed/)
 assert.match(source, /update:page/)
 assert.match(source, /update:pageSize/)
 assert.match(source, /name="mobile"/)
 assert.doesNotMatch(source, /mobileItems\?: Record<string, unknown>\[\]/)
 assert.doesNotMatch(source, /tableKey\?: string/)
 assert.doesNotMatch(source, /columnLabels\?: Record<string, string>/)
 assert.doesNotMatch(source, /columnSettingsLabel\?: string/)
})

test('EntityListView exposes controller-first CRUD page shell contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/views/EntityListView.vue'))
 assert.match(source, /interface EntityListViewProps/)
 assert.match(source, /rowKey: string/)
 assert.match(source, /title\?: string/)
 assert.match(source, /queryFields\?: ResourceCrudQueryField\[\]/)
 assert.match(source, /controller\?: ResourceCrudController/)
 assert.match(source, /const dialogOpen = ref\(false\)/)
 assert.match(source, /const dialogMode = ref<'create' \| 'edit'>\('create'\)/)
 assert.match(source, /runQuery\(/)
 assert.match(source, /setControllerState/)
 assert.match(source, /props\.controller\?\.handlers\?\.query/)
 assert.match(source, /props\.controller\?\.handlers\?\.save/)
 assert.match(source, /props\.controller\?\.handlers\?\.remove/)
 assert.match(source, /props\.controller\?\.handlers\?\.actions/)
 assert.match(source, /props\.controller\?\.actions\?\.actions/)
 assert.match(source, /props\.controller\?\.state\?\.queryValues/)
 assert.match(source, /const defaultRowActions = computed<ResourceCrudRowAction\[]>\(\(\) =>/)
 assert.match(source, /dispatchAction\(/)
 assert.match(source, /resolveActionVariant\(/)
 assert.match(source, /handleFormMutation\(/)
 assert.match(source, /resetDirty\(/)
 assert.match(source, /function requestCancel\(/)
 assert.match(source, /@click="requestCancel"/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="query-fields"/)
 assert.match(source, /slot name="table"/)
 assert.match(source, /slot name="loading"/)
 assert.match(source, /slot name="error"/)
 assert.match(source, /slot name="empty"/)
 assert.match(source, /slot name="batch-actions"/)
 assert.match(source, /slot name="dialog"/)
 assert.match(source, /slot name="detail"/)
 assert.match(source, /LoadingState/)
 assert.match(source, /visibleActions/)
 assert.match(source, /visibleBatchActions/)
 assert.match(source, /resolvedDetailFields/)
 assert.match(source, /hasDetail = computed/)
 assert.doesNotMatch(source, /filters\?: ResourceCrudFilterField\[\]/)
 assert.doesNotMatch(source, /filterValues\?: Record<string, string>/)
 assert.doesNotMatch(source, /selectedRowKeys\?: RowSelectionKey\[\]/)
 assert.doesNotMatch(source, /actions\?: ResourceAction\[\]/)
 assert.doesNotMatch(source, /loading\?: boolean/)
 assert.doesNotMatch(source, /error\?: boolean \| string/)
 assert.doesNotMatch(source, /subtitle\?: string/)
 assert.doesNotMatch(source, /description\?: string/)
 assert.doesNotMatch(source, /eyebrow\?: string/)
 assert.doesNotMatch(source, /statusText\?: string/)
})

test('resource-crud metadata types rely on key-only lookup instead of inline labels or explicit i18n keys', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/views/resource-crud-types.ts'))
 assert.match(source, /export type RowSelectionKey = string/)
 assert.match(source, /export type ResourceCrudColumn = \{/) 
 assert.match(source, /export type ResourceCrudQueryOption = \{/) 
 assert.match(source, /value: string/)
 assert.match(source, /export type ResourceCrudActionHandlerPayload = \{/) 
 assert.match(source, /queryValues: Record<string, string>/)
 assert.match(source, /actions\?: Record<string, ResourceCrudCustomActionHandler>/)
 assert.match(source, /key: string/)
 assert.doesNotMatch(source, /string \| number/)
 assert.doesNotMatch(source, /onClick\?: \(payload:/)
 assert.doesNotMatch(source, /onClick: \(row:/)
 assert.doesNotMatch(source, /label: string/)
 assert.doesNotMatch(source, /i18nKey\?: string/)
 assert.doesNotMatch(source, /placeholderI18nKey\?: string/)
 assert.doesNotMatch(source, /descriptionI18nKey\?: string/)
 assert.doesNotMatch(source, /hintI18nKey\?: string/)
 assert.doesNotMatch(source, /label\?: string/)
 assert.doesNotMatch(source, /title\?: string/)
 assert.doesNotMatch(source, /placeholder\?: string/)
 assert.doesNotMatch(source, /hint\?: string/)
 assert.doesNotMatch(source, /description\?: string/)
})

test('SimpleTablePanel exposes subtitle rowsLabel and actions slot contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/SimpleTablePanel.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /rowsLabel\?: string/)
 assert.match(source, /slot name="actions"/)
})

test('FormPanel exposes sectioned form, summary, and footer action contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/FormPanel.vue'))
 assert.match(source, /interface FormPanelProps/)
 assert.match(source, /sections\?: FormSection\[\]/)
 assert.match(source, /summary\?: string/)
 assert.match(source, /requiredHint\?: string/)
 assert.match(source, /dirty\?: boolean/)
 assert.match(source, /footer\?: FormPanelFooter/)
 assert.match(source, /resolvedFooter = computed/)
 assert.match(source, /slot name="summary"/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="footer"/)
 assert.match(source, /'submit'/)
 assert.match(source, /'cancel'/)
 assert.doesNotMatch(source, /showFooterActions\?: boolean/)
 assert.doesNotMatch(source, /interface FormPanelProps[\s\S]*?dirtyLabel\?: string/)
 assert.doesNotMatch(source, /interface FormPanelProps[\s\S]*?submitLabel\?: string/)
})

test('DashboardCardPanel exposes eyebrow contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/DashboardCardPanel.vue'))
 assert.match(source, /eyebrow\?: string/)
 assert.match(source, /dashboardcardpanel__value/)
})

test('DetailPanel exposes richer detail grid contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/DetailPanel.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /description\?: string/)
 assert.match(source, /fieldsLabel\?: string/)
 assert.match(source, /columns\?: 1 \| 2 \| 3/)
 assert.match(source, /emptyText\?: string/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="footer"/)
})

test('MasterDetailPanel exposes split panel, header action, and detail empty-state contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/MasterDetailPanel.vue'))
 assert.match(source, /interface MasterDetailPanelProps/)
 assert.match(source, /splitRatio\?: string/)
 assert.match(source, /masterTitle\?: string/)
 assert.match(source, /detailTitle\?: string/)
 assert.match(source, /detailEmptyTitle\?: string/)
 assert.match(source, /detailEmptyDescription\?: string/)
 assert.match(source, /slot name="header-actions"/)
 assert.match(source, /slot name="master"/)
 assert.match(source, /name="detail"/)
})

test('CrudDialog exposes dialog mode, footer action, dirty-close guard, and close contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/CrudDialog.vue'))
 assert.match(source, /interface CrudDialogProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /summary\?: string/)
 assert.match(source, /size\?: 'sm' \| 'md' \| 'lg'/)
 assert.match(source, /closeOnBackdrop\?: boolean/)
 assert.match(source, /guardDirtyClose\?: boolean/)
 assert.match(source, /footer\?: \{/)
 assert.match(source, /resolvedFooter = computed/)
 assert.match(source, /'update:modelValue'/)
 assert.match(source, /'submit'/)
 assert.match(source, /'cancel'/)
 assert.match(source, /'close'/)
 assert.match(source, /'request-close'/)
 assert.match(source, /const shouldGuardClose = computed/)
 assert.match(source, /emit\('request-close', \{ source \}\)/)
 assert.match(source, /emit\('cancel'\)/)
 assert.match(source, /emit\('update:modelValue', false\)/)
 assert.match(source, /slot name="header-actions"/)
 assert.match(source, /slot name="summary"/)
 assert.match(source, /slot name="footer"/)
 assert.doesNotMatch(source, /showFooterActions\?: boolean/)
})

test('ReportPanel exposes query/result/export contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/panels/ReportPanel.vue'))
 assert.match(source, /interface ReportPanelProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /description\?: string/)
 assert.match(source, /query\?: \{/)
 assert.match(source, /result\?: \{/)
 assert.match(source, /resolvedQuery = computed/)
 assert.match(source, /resolvedResult = computed/)
 assert.match(source, /exportable\?: boolean/)
 assert.match(source, /exportLabel: '导出'/)
 assert.match(source, /title: '查询条件'/)
 assert.match(source, /emptyText: '未配置报表查询条件。'/)
 assert.match(source, /title: '结果列表'/)
 assert.match(source, /emptyText: '暂无报表结果。'/)
 assert.match(source, /'export'/)
 assert.match(source, /slot name="query"/)
 assert.match(source, /slot name="result"/)
 assert.match(source, /slot name="header-actions"/)
 assert.match(source, /slot name="result-actions"/)
 assert.doesNotMatch(source, /queryTitle\?: string/)
 assert.doesNotMatch(source, /resultTitle\?: string/)
})

test('ColumnSettings exposes visibleKeys show-all and reset contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/interaction/ColumnSettings.vue'))
 assert.match(source, /visibleKeys\?: string\[\]/)
 assert.match(source, /showAllLabel\?: string/)
 assert.match(source, /'update:visibleKeys'/)
 assert.match(source, /'show-all'/)
 assert.match(source, /'reset'/)
})

test('ActionBar exposes schema-driven action layout contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/interaction/ActionBar.vue'))
 assert.match(source, /type ActionBarItem/)
 assert.match(source, /actions\?: ActionBarItem\[\]/)
 assert.match(source, /align\?: 'start' \| 'between' \| 'end'/)
 assert.match(source, /busy\?: boolean/)
 assert.match(source, /visibleActions/)
})

test('Form and dialog shell defaults use consistent Chinese copy', () => {
 const formSource = read(path.join(repoRoot, 'packages/vue/src/components/panels/FormPanel.vue'))
 const dialogSource = read(path.join(repoRoot, 'packages/vue/src/components/panels/CrudDialog.vue'))
 const detailSource = read(path.join(repoRoot, 'packages/vue/src/components/panels/DetailPanel.vue'))
 const columnSource = read(path.join(repoRoot, 'packages/vue/src/components/interaction/ColumnSettings.vue'))
 const simpleTableSource = read(path.join(repoRoot, 'packages/vue/src/components/panels/SimpleTablePanel.vue'))
 assert.match(formSource, /emptyText: '未配置表单分组。'/)
 assert.match(formSource, /dirtyLabel: '存在未保存修改'/)
 assert.match(formSource, /submitLabel: '保存'/)
 assert.match(formSource, /cancelLabel: '取消'/)
 assert.match(dialogSource, /dirtyLabel: '存在未保存修改'/)
 assert.match(dialogSource, /submitLabel: '保存'/)
 assert.match(dialogSource, /cancelLabel: '取消'/)
 assert.match(dialogSource, /closeLabel: '关闭'/)
 assert.match(detailSource, /fieldsLabel: '字段数：'/)
 assert.match(detailSource, /emptyText: '暂无详情字段。'/)
 assert.match(columnSource, /label: '列设置'/)
 assert.match(columnSource, /resetLabel: '重置'/)
 assert.match(columnSource, /showAllLabel: '显示全部'/)
 assert.match(simpleTableSource, /rowsLabel: '当前行数：'/)
})

test('LoadingState EmptyState and ErrorState expose richer state contracts', () => {
 const loadingSource = read(path.join(repoRoot, 'packages/vue/src/components/interaction/LoadingState.vue'))
 const emptySource = read(path.join(repoRoot, 'packages/vue/src/components/interaction/EmptyState.vue'))
 const errorSource = read(path.join(repoRoot, 'packages/vue/src/components/interaction/ErrorState.vue'))
 assert.match(loadingSource, /interface LoadingStateProps/)
 assert.match(loadingSource, /message\?: string/)
 assert.match(emptySource, /icon\?: string/)
 assert.match(emptySource, /slot name="actions"/)
 assert.match(errorSource, /icon\?: string/)
 assert.match(errorSource, /slot name="actions"/)
})

test('Pagination exposes pageCount pageSizeOptions and update emits contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/interaction/Pagination.vue'))
 assert.match(source, /pageCount\?: number/)
 assert.match(source, /pageSizeOptions\?: number\[\]/)
 assert.match(source, /pageSizeLabel: '每页条数'/)
 assert.match(source, /summaryLabel: '页码'/)
 assert.match(source, /previousLabel: '上一页'/)
 assert.match(source, /nextLabel: '下一页'/)
 assert.match(source, /'update:page'/)
 assert.match(source, /'update:pageSize'/)
})

test('StatusChip constrains tone variants', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/interaction/StatusChip.vue'))
 assert.match(source, /new Set\(\['neutral', 'success', 'warning', 'danger', 'info'\]\)/)
})

test('DataTable exposes simplified renderers visible columns row actions and row selection contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/components/interaction/DataTable.vue'))
 assert.match(source, /type CellRenderer = 'text' \| 'status' \| 'tags'/)
 assert.match(source, /rowKey: string/)
 assert.match(source, /visibleColumnKeys\?: string\[\]/)
 assert.match(source, /actionsLabel\?: string/)
 assert.match(source, /rowActions\?: RowAction\[\]/)
 assert.match(source, /selectable\?: boolean/)
 assert.match(source, /selectedRowKeys\?: RowSelectionKey\[\]/)
 assert.match(source, /selectionLabel\?: string/)
 assert.match(source, /visible\?: boolean/)
 assert.match(source, /inferredColumns/)
 assert.match(source, /getCurrentInstance/)
 assert.match(source, /resolveLabel/)
 assert.match(source, /inferRenderer/)
 assert.match(source, /resolveRowKey/)
 assert.match(source, /'row-click'/)
 assert.match(source, /'update:selectedRowKeys'/)
 assert.match(source, /toggleSelectAll/)
 assert.match(source, /toggleRowSelection/)
 assert.match(source, /StatusChip/)
 assert.match(source, /AppTag/)
 assert.doesNotMatch(source, /columnLabels\?: Record<string, string>/)
 assert.doesNotMatch(source, /toneMap\?: Record<string, string>/)
})

