import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const repoRoot = path.resolve(new URL('..', import.meta.url).pathname)

function read(path) {
 return fs.readFileSync(path, 'utf8')
}

test('EntityListTable exposes simplified typed props contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/EntityListTable.vue'))
 assert.match(source, /interface EntityListTableProps/)
 assert.match(source, /rowKey: string/)
 assert.match(source, /columns\?: InputColumn\[\]/)
 assert.match(source, /items\?: Record<string, unknown>\[\]/)
 assert.doesNotMatch(source, /mobileItems\?: Record<string, unknown>\[\]/)
 assert.doesNotMatch(source, /tableKey\?: string/)
 assert.doesNotMatch(source, /columnLabels\?: Record<string, string>/)
})

test('PermissionGuard exposes granted prop', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/PermissionGuard.vue'))
 assert.match(source, /granted\?: boolean/)
 assert.match(source, /slot name="fallback"/)
})

test('PermissionAwareAction exposes granted-only contract with slot content', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/interaction/PermissionAwareAction.vue'))
 assert.match(source, /interface PermissionAwareActionProps/)
 assert.match(source, /granted\?: boolean/)
 assert.doesNotMatch(source, /label\?: string/)
 assert.match(source, /<slot \/>/)
})

test('MainPage exposes concrete shell and global agent contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/pages/MainPage.vue'))
 assert.match(source, /interface MainPageProps/)
 assert.match(source, /agentSessionsOpen\?: boolean/)
 assert.doesNotMatch(source, /showSidebar\?: boolean/)
 assert.doesNotMatch(source, /dense\?: boolean/)
 assert.doesNotMatch(source, /iconOnly\?: boolean/)
 assert.doesNotMatch(source, /orgCode\?: string/)
 assert.doesNotMatch(source, /topbarSubtitle\?: string/)
 assert.doesNotMatch(source, /userSubtitle\?: string/)
 assert.doesNotMatch(source, /showAgentBar\?: boolean/)
 assert.doesNotMatch(source, /userDisplayName\?: string/)
 assert.doesNotMatch(source, /username\?: string/)
 assert.match(source, /slot name="sidebar"/)
 assert.match(source, /resolveCopy\('efs\.shell\.mobileMenuLabel'/)
 assert.match(source, /resolveCopy\('efs\.shell\.profileDialog\.label'/)
 assert.match(source, /resolveCopy\('efs\.shell\.passwordDialog\.label'/)
 assert.match(source, /slot name="toolbar"/)
 assert.match(source, /slot name="alerts"/)
 assert.match(source, /slot name="agent-sessions"/)
 assert.match(source, /slot name="agent-output"/)
 assert.match(source, /submit-agent/)
 assert.match(source, /submit-profile/)
 assert.match(source, /submit-password/)
 assert.match(source, /update:agentSessionsOpen/)
 assert.match(source, /import LocaleSwitcher from '\.\.\/controls\/LocaleSwitcher\.vue'/)
 assert.match(source, /import ThemeSwitcher from '\.\.\/controls\/ThemeSwitcher\.vue'/)
 assert.match(source, /import GlobalAlertsHost from '\.\.\/interaction\/GlobalAlertsHost\.vue'/)
 assert.match(source, /useAppAlerts/)
 assert.match(source, /<LocaleSwitcher/)
 assert.match(source, /mode="icon"/)
 assert.match(source, /<ThemeSwitcher/)
 assert.match(source, /<GlobalAlertsHost/)
 assert.match(source, /import SemanticIcon from '\.\.\/controls\/SemanticIcon\.vue'/)
 assert.match(source, /<SemanticIcon name="menu"/)
 assert.match(source, /<SemanticIcon name="more"/)
 assert.match(source, /<SemanticIcon name="user"/)
 assert.match(source, /<SemanticIcon name="lock"/)
 assert.match(source, /<SemanticIcon name="send"/)
 assert.doesNotMatch(source, /profileLabel\?: string/)
 assert.doesNotMatch(source, /passwordLabel\?: string/)
 assert.doesNotMatch(source, /saveLabel\?: string/)
 assert.doesNotMatch(source, /usernameLabel:/)
})

test('SemanticIcon exposes unified semantic token contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/SemanticIcon.vue'))
 assert.match(source, /interface SemanticIconProps/)
 assert.match(source, /name\?: string/)
 assert.match(source, /fallback\?: string/)
 assert.match(source, /label\?: string/)
 assert.match(source, /size\?: 'sm' \| 'md' \| 'lg'/)
 assert.match(source, /resolveSemanticIcon/)
})

test('EfsApp exposes single-component app-shell contract around LegacyAppController', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/pages/EfsApp.vue'))
 const indexSource = read(path.join(repoRoot, 'packages/vue/src/index.ts'))
 assert.match(source, /defineOptions\(\{ name: 'EfsApp' \}\)/)
 assert.match(source, /interface EfsAppProps/)
 assert.match(source, /app: LegacyAppController/)
 assert.match(source, /appName\?: string/)
 assert.match(source, /brandIcon\?: string/)
 assert.match(source, /theme\?: 'light' \| 'dark'/)
 assert.match(source, /i18n\?: EfsI18nConfig/)
 assert.doesNotMatch(source, /title\?: string/)
 assert.doesNotMatch(source, /locale\?: string/)
 assert.doesNotMatch(source, /runtimeOptions\?: ResCrudRuntimeOptions & ResReportRuntimeOptions/)
 assert.doesNotMatch(source, /subtitle\?: string/)
 assert.doesNotMatch(source, /brandTitle\?: string/)
 assert.doesNotMatch(source, /brandSubtitle\?: string/)
 assert.doesNotMatch(source, /loginTitle\?: string/)
 assert.doesNotMatch(source, /useRoute\(/)
 assert.doesNotMatch(source, /useRouter\(/)
 assert.doesNotMatch(source, /const shell = computed\(\(\) => props\.app\.shell \?\? \{\}\)/)
 assert.match(source, /const initialLocale = computed\(\(\) => props\.i18n\?\.locale \|\| 'zh-CN'\)/)
 assert.match(source, /const initialTheme = computed<'light' \| 'dark'>\(\(\) => props\.theme === 'light' \? 'light' : 'dark'\)/)
 assert.match(source, /mergeEfsI18nConfigs\(props\.i18n, \{ locale: locale\.value \}\)/)
 assert.match(source, /watch\(initialLocale, \(value\) => \{/)
 assert.match(source, /watch\(initialTheme, \(value\) => \{/)
 assert.match(source, /provide\(EFS_I18N_CONTEXT, \{/)
 assert.match(source, /const sidebarMenus = computed<FlatMenuNode\[\]>\(\(\) => flattenAppMenuNodes\(props\.app\)\)/)
 assert.match(source, /resolveResRuntime\(props\.app, currentPath/)
 assert.match(source, /const resolvedBrandTitle = computed\(\(\) => resolveCopy\('efs\.brand\.title'/)
 assert.match(source, /const resolvedMainTitle = computed\(\(\) => runtime\.value\?\.title \|\| resolvedEmptyTitle\.value\)/)
 assert.match(source, /<MainPage/)
 assert.match(source, /:app-name="props\.appName \|\| ''"/)
 assert.match(source, /@update:org="handleOrgCodeUpdate"/)
 assert.match(source, /<EfsSidebarNav :items="sidebarMenus" :current-path="currentPath" @navigate="handleNavigate" \/>/)
 assert.match(source, /<slot v-if="\$slots\.default" \/>/)
 assert.match(source, /<ResolvedResPage/)
 assert.match(source, /@logout="handleLogout"/)
 assert.match(source, /const theme = ref<'light' \| 'dark'>\('dark'\)/)
 assert.match(source, /useEfsNavigation\(/)
 assert.match(source, /login: props\.app\.auth\.login/)
 assert.match(source, /status: authStatus/)
 assert.match(source, /token: authToken/)
 assert.doesNotMatch(source, /props\.app\.auth\.name\.value/)
 assert.doesNotMatch(source, /props\.app\.auth\.pwd\.value/)
 assert.doesNotMatch(source, /props\.app\.auth\.orgCode\?\.value/)
 assert.doesNotMatch(source, /props\.app\.auth\.authenticated\?\.value/)
 assert.doesNotMatch(source, /props\.app\.auth\.busy\?\.value/)
 assert.doesNotMatch(source, /props\.app\.auth\.error\?\.value/)
 assert.doesNotMatch(source, /props\.app\.main\.currentPath\.value/)
 assert.doesNotMatch(source, /emit\('update:locale'/)
 assert.doesNotMatch(source, /emit\('update:theme'/)
 assert.doesNotMatch(indexSource, /export type \* from '\.\/components\/pages\/efs-app-types'/)
 assert.match(indexSource, /export \{ default as EfsApp \} from '\.\/pages\/EfsApp\.vue'/)
 assert.doesNotMatch(indexSource, /export \{ default as EfsSidebarNav \} from '\.\/pages\/EfsSidebarNav\.vue'/)
 assert.doesNotMatch(indexSource, /export \{ default as ResolvedResPage \} from '\.\/pages\/ResolvedResPage\.vue'/)
})

test('ResolvedResPage exposes shared runtime-kind shell contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/pages/ResolvedResPage.vue'))
 const indexSource = read(path.join(repoRoot, 'packages/vue/src/index.ts'))
 assert.match(source, /defineOptions\(\{ name: 'ResolvedResPage' \}\)/)
 assert.match(source, /interface ResolvedResPageProps/)
 assert.match(source, /runtime\?: ResRuntime \| null/)
 assert.match(source, /path\?: string/)
 assert.match(source, /const crudRuntime = computed\(\(\) => props\.runtime\?\.kind === 'crud' \? props\.runtime : null\)/)
 assert.match(source, /resolveCopy\('efs\.runtime\.crudSubtitle'/)
 assert.match(source, /const reportRuntime = computed\(\(\) => props\.runtime\?\.kind === 'report' \? props\.runtime : null\)/)
 assert.match(source, /v-if="crudRuntime"/)
 assert.match(source, /v-else-if="reportRuntime"/)
 assert.match(source, /:detail-fields="crudRuntime\.detailFields\.value"/)
 assert.match(source, /<EntityListView/)
 assert.match(source, /<ReportView/)
 assert.match(source, /v-if="props\.path"/)
 assert.match(source, /当前路径：\{\{ props\.path \}\}/)
 assert.doesNotMatch(indexSource, /export \{ default as ResolvedResPage \} from '\.\/components\/pages\/ResolvedResPage\.vue'/)
})

test('AuthPage exposes stronger auth-shell props and slots contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/pages/AuthPage.vue'))
 assert.match(source, /interface AuthPageProps/)
 assert.match(source, /locale\?: string/)
 assert.match(source, /theme\?: string/)
 assert.doesNotMatch(source, /title\?: string/)
 assert.doesNotMatch(source, /subtitle\?: string/)
 assert.doesNotMatch(source, /heroTitle\?: string/)
 assert.doesNotMatch(source, /heroSubtitle\?: string/)
 assert.doesNotMatch(source, /maxWidth\?: string/)
 assert.doesNotMatch(source, /layout\?: 'centered' \| 'split'/)
 assert.doesNotMatch(source, /panelWidth\?: string/)
 assert.doesNotMatch(source, /showLocaleSwitcher\?: boolean/)
 assert.doesNotMatch(source, /showThemeSwitcher\?: boolean/)
 assert.match(source, /slot name="brand"/)
 assert.match(source, /showTopBar/)
 assert.match(source, /efs-auth-layout__topbar/)
 assert.match(source, /slot name="header"/)
 assert.match(source, /slot name="alerts"/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="locale-action"/)
 assert.match(source, /slot name="theme-action"/)
 assert.match(source, /slot name="footer"/)
 assert.match(source, /<LocaleSwitcher :model-value="props\.locale" @update:model-value=/)
 assert.match(source, /<ThemeSwitcher :model-value="props\.theme" @update:model-value=/)
 assert.match(source, /import LocaleSwitcher from '\.\.\/controls\/LocaleSwitcher\.vue'/)
 assert.match(source, /import ThemeSwitcher from '\.\.\/controls\/ThemeSwitcher\.vue'/)
 assert.match(source, /import GlobalAlertsHost from '\.\.\/interaction\/GlobalAlertsHost\.vue'/)
 assert.match(source, /useAppAlerts/)
 assert.match(source, /<GlobalAlertsHost/)
 assert.match(source, /update:locale/)
 assert.match(source, /update:theme/)
 assert.doesNotMatch(source, /centered\?: boolean/)
})

test('LocaleSwitcher and ThemeSwitcher expose standard switch contracts', () => {
 const localeSource = read(path.join(repoRoot, 'packages/vue/src/controls/LocaleSwitcher.vue'))
 const themeSource = read(path.join(repoRoot, 'packages/vue/src/controls/ThemeSwitcher.vue'))
 assert.match(localeSource, /interface LocaleSwitcherProps/)
 assert.match(localeSource, /modelValue\?: string/)
 assert.match(localeSource, /mode\?: 'pill' \| 'menu' \| 'icon'/)
 assert.match(localeSource, /update:modelValue/)
 assert.match(localeSource, /SemanticIcon/)
 assert.doesNotMatch(localeSource, /interface LocaleSwitcherProps \{[\s\S]*label\?: string/)
 assert.doesNotMatch(localeSource, /interface LocaleSwitcherProps \{[\s\S]*options\?: LocaleOption\[\]/)
 assert.match(localeSource, /const resolvedLabel = computed\(\(\) => resolveCopy\('efs\.shell\.localeLabel'/)
 assert.match(localeSource, /const resolvedOptions = computed<LocaleOption\[]>\(\(\) => \[/)
 assert.match(themeSource, /interface ThemeSwitcherProps/)
 assert.match(themeSource, /modelValue\?: string/)
 assert.match(themeSource, /mode\?: 'pill' \| 'menu' \| 'icon'/)
 assert.match(themeSource, /update:modelValue/)
 assert.match(themeSource, /SemanticIcon/)
 assert.doesNotMatch(themeSource, /interface ThemeSwitcherProps \{[\s\S]*label\?: string/)
 assert.doesNotMatch(themeSource, /interface ThemeSwitcherProps \{[\s\S]*options\?: ThemeOption\[\]/)
 assert.match(themeSource, /const resolvedLabel = computed\(\(\) => resolveCopy\('efs\.shell\.themeLabel'/)
 assert.match(themeSource, /const resolvedOptions = computed<ThemeOption\[]>\(\(\) => \[/)
})

test('AppAlerts and global alerts host expose reusable global alert contracts', () => {
 const alertsSource = read(path.join(repoRoot, 'packages/vue/src/interaction/AppAlerts.vue'))
 const hostSource = read(path.join(repoRoot, 'packages/vue/src/interaction/GlobalAlertsHost.vue'))
 const storeSource = read(path.join(repoRoot, 'packages/vue/src/shared/app-alerts.ts'))
 assert.match(alertsSource, /interface AppAlertsProps/)
 assert.match(alertsSource, /items\?: AppAlertItem\[\]/)
 assert.match(alertsSource, /\(e: 'close', key: string\): void/)
 assert.match(hostSource, /useAppAlerts/)
 assert.match(hostSource, /<AppAlerts :items="mutableItems" @close="remove" \/>/)
 assert.match(hostSource, /const mutableItems = computed\(\(\) => \[\.\.\.items\.value\]\)/)
 assert.match(storeSource, /export type AppAlertItem = \{/) 
 assert.match(storeSource, /export function useAppAlerts\(\)/)
 assert.match(storeSource, /success\(/)
 assert.match(storeSource, /warning\(/)
 assert.match(storeSource, /danger\(/)
})

test('LegacyAppController types expose app/main/domain/res contract and typed domain-res path helpers', () => {
 const barrelSource = read(path.join(repoRoot, 'packages/vue/src/legacy/index.ts'))
 const typesBarrelSource = read(path.join(repoRoot, 'packages/vue/src/legacy/types.ts'))
 const sharedTypesSource = read(path.join(repoRoot, 'packages/vue/src/legacy/shared-types.ts'))
 const resControllerSource = read(path.join(repoRoot, 'packages/vue/src/legacy/res-controller.ts'))
 const domainControllerSource = read(path.join(repoRoot, 'packages/vue/src/legacy/domain-controller.ts'))
 const mainControllerSource = read(path.join(repoRoot, 'packages/vue/src/legacy/main-controller.ts'))
 const authControllerSource = read(path.join(repoRoot, 'packages/vue/src/legacy/auth-controller.ts'))
 const appControllerSource = read(path.join(repoRoot, 'packages/vue/src/legacy/app-controller.ts'))
 const i18nSource = read(path.join(repoRoot, 'packages/vue/src/shared/efs-i18n.ts'))
 const pathHelpersSource = read(path.join(repoRoot, 'packages/vue/src/legacy/path-helpers.ts'))
 const inferenceSource = read(path.join(repoRoot, 'packages/vue/src/legacy/field-inference.ts'))
 const runtimeSource = read(path.join(repoRoot, 'packages/vue/src/legacy/runtime.ts'))
 const indexSource = read(path.join(repoRoot, 'packages/vue/src/index.ts'))

 assert.match(barrelSource, /export type \{/)
 assert.match(barrelSource, /LegacyAppController/)
 assert.match(barrelSource, /LegacyAuthController/)
 assert.match(barrelSource, /LegacyDomainController/)
 assert.match(barrelSource, /LegacyMainController/)
 assert.match(barrelSource, /LegacyResController/)
 assert.doesNotMatch(barrelSource, /buildResPath/)
 assert.doesNotMatch(barrelSource, /flattenAppMenuNodes/)
 assert.doesNotMatch(barrelSource, /resolveResRuntime/)
 assert.doesNotMatch(barrelSource, /export \* from '\.\/field-inference'/)
 assert.doesNotMatch(barrelSource, /export \* from '\.\/runtime'/)
 assert.doesNotMatch(barrelSource, /buildResCrudRuntime/)
 assert.doesNotMatch(barrelSource, /buildResReportRuntime/)
 assert.doesNotMatch(barrelSource, /inferFieldUses/)
 assert.doesNotMatch(barrelSource, /inferFieldOrder/)
 assert.doesNotMatch(barrelSource, /inferListColumns/)

 assert.match(typesBarrelSource, /export \* from '\.\/shared-types'/)
 assert.match(typesBarrelSource, /export \* from '\.\/res-controller'/)
 assert.match(typesBarrelSource, /export \* from '\.\/domain-controller'/)
 assert.match(typesBarrelSource, /export \* from '\.\/main-controller'/)
 assert.match(typesBarrelSource, /export \* from '\.\/auth-controller'/)
 assert.match(typesBarrelSource, /export \* from '\.\/app-controller'/)

 assert.match(sharedTypesSource, /export type DomainResPath<.*> = `\$\{D\}\/\$\{R\}`/)
 assert.match(sharedTypesSource, /export type MenuOrder = number/)
 assert.match(sharedTypesSource, /export type FieldUse = 'query' \| 'list' \| 'form' \| 'detail'/)
 assert.match(sharedTypesSource, /export type ResFieldKind = 'text' \| 'number' \| 'bool' \| 'date' \| 'datetime' \| 'enum' \| 'ref' \| 'tags' \| 'json'/)
 assert.match(sharedTypesSource, /export type ResFieldQueryType = 'text' \| 'search' \| 'date' \| 'number' \| 'select'/)
 assert.match(sharedTypesSource, /export type ResFieldWidget = 'text' \| 'number' \| 'switch' \| 'date' \| 'select' \| 'tags' \| 'json'/)
 assert.match(sharedTypesSource, /export type ResFieldRender = ResourceCrudColumn\['render'\]/)
 assert.match(sharedTypesSource, /export type ResEnumField<.*>/)
 assert.match(sharedTypesSource, /export type ResRefField<.*>/)
 assert.match(sharedTypesSource, /ref: string/)
 assert.match(sharedTypesSource, /queryType\?: ResFieldQueryType/)
 assert.match(sharedTypesSource, /widget\?: ResFieldWidget/)
 assert.match(sharedTypesSource, /render\?: ResFieldRender/)
 assert.match(sharedTypesSource, /summary\?: boolean/)
 assert.match(sharedTypesSource, /export type ResField<.*> = ResValueField<.*> \| ResSelectField<.*>/)
 assert.match(sharedTypesSource, /export type AuthOption = \{/) 
 assert.match(sharedTypesSource, /export interface ResCrudRuntimeOptions/)
 assert.match(sharedTypesSource, /pageSizeOptions\?: number\[\]/)
 assert.match(sharedTypesSource, /selectableRows\?: boolean/)
 assert.match(sharedTypesSource, /export interface ResReportRuntimeOptions/)
 assert.match(sharedTypesSource, /export interface ResCrudRuntime/)
 assert.match(sharedTypesSource, /kind: 'crud'/)
 assert.match(sharedTypesSource, /export interface ResReportRuntime/)
 assert.match(sharedTypesSource, /kind: 'report'/)
 assert.match(sharedTypesSource, /controller: ReportViewController/)
 assert.match(sharedTypesSource, /export type ResRuntime = ResCrudRuntime \| ResReportRuntime/)
 assert.match(sharedTypesSource, /pageSizeOptions: number\[\]/)
 assert.match(sharedTypesSource, /selectableRows: boolean/)

 assert.match(resControllerSource, /export interface LegacyResController<.*>/)
 assert.match(resControllerSource, /kind: 'res'/)
 assert.match(resControllerSource, /domain: D/)
 assert.match(resControllerSource, /res: R/)
 assert.match(resControllerSource, /icon\?: string/)
 assert.match(resControllerSource, /order\?: MenuOrder/)
 assert.match(resControllerSource, /runtimeKind\?: 'crud' \| 'report'/)
 assert.match(resControllerSource, /summary: ReportViewSummaryMetric\[\]/)
 assert.match(resControllerSource, /report\?: readonly ReportViewAction\[\]/)

 assert.match(domainControllerSource, /export interface LegacyDomainController<.*>/)
 assert.match(domainControllerSource, /kind: 'domain'/)
 assert.match(domainControllerSource, /items: readonly LegacyResController<D, string>\[\]/)

 assert.match(mainControllerSource, /export interface LegacyMainController/)
 assert.match(mainControllerSource, /kind: 'main'/)
 assert.match(mainControllerSource, /domains: readonly LegacyDomainController\[\]/)
 assert.match(mainControllerSource, /defaultPath\?: DomainResPath \| ''/)
 assert.doesNotMatch(mainControllerSource, /currentPath\?: Ref<DomainResPath \| ''>/)

 assert.match(authControllerSource, /export interface LegacyAuthController/)
 assert.match(authControllerSource, /kind: 'auth'/)
 assert.match(authControllerSource, /export interface AuthLoginInput/)
 assert.match(authControllerSource, /name: string/)
 assert.match(authControllerSource, /pwd: string/)
 assert.match(authControllerSource, /export interface AuthLoginResult/)
 assert.match(authControllerSource, /accessToken: string/)
 assert.match(authControllerSource, /login: \(input: AuthLoginInput\) => AuthLoginResult \| Promise<AuthLoginResult>/)
 assert.match(authControllerSource, /getOrgs\?: \(\) => readonly AuthOption\[\] \| Promise<readonly AuthOption\[\]>/)
 assert.match(authControllerSource, /getCurrentOrgCode\?: \(\) => string \| undefined/)
 assert.match(authControllerSource, /setCurrentOrgCode\?: \(orgCode: string\) => void \| Promise<void>/)
 assert.doesNotMatch(authControllerSource, /name: Ref<string>/)
 assert.doesNotMatch(authControllerSource, /pwd: Ref<string>/)
 assert.doesNotMatch(authControllerSource, /orgCode\?: Ref<string>/)
 assert.doesNotMatch(authControllerSource, /orgOptions\?: readonly AuthOption\[\]/)
 assert.doesNotMatch(authControllerSource, /busy\?: Ref<boolean>/)
 assert.doesNotMatch(authControllerSource, /error\?: Ref<string>/)
 assert.doesNotMatch(authControllerSource, /authenticated\?: Ref<boolean>/)

 assert.match(appControllerSource, /export interface LegacyAppController/)
 assert.match(appControllerSource, /kind: 'app'/)
 assert.doesNotMatch(appControllerSource, /appName\?: string/)
 assert.doesNotMatch(appControllerSource, /export interface AppShellConfig/)
 assert.doesNotMatch(appControllerSource, /shell\?: AppShellConfig/)
 assert.match(appControllerSource, /auth: LegacyAuthController/)
 assert.match(appControllerSource, /main: LegacyMainController/)
 assert.match(i18nSource, /export interface EfsI18nConfig/)
 assert.match(i18nSource, /messages\?: EfsI18nMessages \| Record<string, EfsI18nMessages>/)
 assert.match(i18nSource, /resolveEfsI18nLabel/)

 assert.match(pathHelpersSource, /export function buildResPath/)
 assert.match(pathHelpersSource, /export function splitResPath/)
 assert.match(pathHelpersSource, /export function listAllResControllers/)
 assert.match(pathHelpersSource, /export function findDomainByKey/)
 assert.match(pathHelpersSource, /export function findResByPath/)
 assert.match(pathHelpersSource, /export function flattenAppMenuNodes/)
 assert.match(pathHelpersSource, /export function isResController/)

 assert.match(inferenceSource, /export function inferFieldUses/)
 assert.match(inferenceSource, /export function inferFieldOrder/)
 assert.match(inferenceSource, /export function inferListColumns/)
 assert.match(inferenceSource, /if \(field\.render\) return field\.render/)
 assert.match(inferenceSource, /export function inferQueryFields/)
 assert.match(inferenceSource, /if \(field\.queryType\) return field\.queryType/)
 assert.match(inferenceSource, /export function inferFormFields/)
 assert.match(inferenceSource, /if \(field\.widget\) return field\.widget/)
 assert.match(inferenceSource, /export function inferFormSections/)
 assert.match(inferenceSource, /export function inferDetailFields/)
 assert.match(inferenceSource, /export function defaultDetailValueFormatter/)
 assert.match(inferenceSource, /inferReportSummaryMetrics/)
 assert.match(inferenceSource, /inferReportColumns/)

 assert.match(runtimeSource, /export function resolveResRuntime/)
 assert.match(runtimeSource, /res\.runtimeKind === 'report'/)
 assert.match(runtimeSource, /return buildResReportRuntime\(app, path, options\)/)
 assert.match(runtimeSource, /return buildResCrudRuntime\(app, path, options\)/)
 assert.match(runtimeSource, /export function buildResReportRuntime/)
 assert.match(runtimeSource, /inferReportSummaryMetrics/)
 assert.match(runtimeSource, /inferReportColumns/)
 assert.match(runtimeSource, /export function buildResCrudRuntime/)
 assert.match(runtimeSource, /pageSizeOptions: options\.pageSizeOptions \?\? \[10, 20, 50\]/)
 assert.match(runtimeSource, /selectableRows: options\.selectableRows \?\? true/)
 assert.match(runtimeSource, /defaultDetailValueFormatter/)

 assert.match(indexSource, /export \{ default as EfsApp \} from '\.\/pages\/EfsApp\.vue'/)
 assert.doesNotMatch(indexSource, /LegacyAppController/)
 assert.doesNotMatch(indexSource, /LegacyAuthController/)
 assert.doesNotMatch(indexSource, /LegacyDomainController/)
 assert.doesNotMatch(indexSource, /LegacyMainController/)
 assert.doesNotMatch(indexSource, /LegacyResController/)
})

test('AppButton exposes foundational action props and slots contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/AppButton.vue'))
 assert.match(source, /interface AppButtonProps/)
 assert.match(source, /size\?: 'sm' \| 'md' \| 'lg'/)
 assert.match(source, /loading\?: boolean/)
 assert.match(source, /block\?: boolean/)
 assert.match(source, /slot name="leading"/)
 assert.match(source, /slot name="trailing"/)
})

test('AppInput exposes foundational form-control props and slots contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/AppInput.vue'))
 assert.match(source, /interface AppInputProps/)
 assert.match(source, /disabled\?: boolean/)
 assert.match(source, /readonly\?: boolean/)
 assert.match(source, /invalid\?: boolean/)
 assert.match(source, /slot name="leading"/)
 assert.match(source, /slot name="trailing"/)
})

test('AppSelect exposes foundational select props contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/AppSelect.vue'))
 assert.match(source, /interface AppSelectProps/)
 assert.match(source, /modelValue\?: string/)
 assert.match(source, /placeholder\?: string/)
 assert.match(source, /disabled\?: boolean/)
 assert.match(source, /optionLabelKey\?: string/)
 assert.match(source, /optionValueKey\?: string/)
 assert.match(source, /optionDisabledKey\?: string/)
 assert.match(source, /update:modelValue', value: string/)
 assert.doesNotMatch(source, /type OptionValue = string \| number/)
})

test('AppField exposes foundational label-help-error contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/AppField.vue'))
 assert.match(source, /interface AppFieldProps/)
 assert.match(source, /hint\?: string/)
 assert.match(source, /error\?: string/)
 assert.match(source, /required\?: boolean/)
})

test('AppPanel exposes foundational panel header actions contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/controls/AppPanel.vue'))
 assert.match(source, /interface AppPanelProps/)
 assert.match(source, /padded\?: boolean/)
 assert.match(source, /borderless\?: boolean/)
 assert.match(source, /slot name="actions"/)
})

test('PagePanel exposes header actions slot contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/PagePanel.vue'))
 assert.match(source, /interface PagePanelProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /slot name="actions"/)
})

test('EntityListTable exposes simplified column settings and pagination contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/EntityListTable.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /showPagination\?: boolean/)
 assert.match(source, /render\?: 'text' \| 'status' \| 'tags'/)
 assert.match(source, /formatter\?: \(value: unknown, row: Record<string, unknown>\) => unknown/)
 assert.match(source, /inferredColumns/)
 assert.match(source, /resolveDisplayValue\(/)
 assert.match(source, /resolveTags\(/)
 assert.match(source, /resolveTone\(/)
 assert.match(source, /summarizeObject\(/)
 assert.match(source, /<StatusChip :tone="resolveTone\(item, column\)">\{\{ displayText\(resolveDisplayValue\(item, column\)\) \}\}<\/StatusChip>/)
 assert.match(source, /<AppTag v-for="tag in resolveTags\(item, column\)"/)
 assert.match(source, /storageKey = computed/)
 assert.match(source, /getCurrentInstance/)
 assert.match(source, /resolveLabel/)
 assert.doesNotMatch(source, /labels\?: EntityListTableLabels/)
 assert.doesNotMatch(source, /resolvedLabels = computed/)
 assert.match(source, /header v-if="props.title \|\| props.subtitle \|\| \$slots\['header-actions'\]/)
 assert.match(source, /update:page/)
 assert.match(source, /update:pageSize/)
 assert.match(source, /name="mobile"/)
 assert.doesNotMatch(source, /mobileItems\?: Record<string, unknown>\[\]/)
 assert.doesNotMatch(source, /tableKey\?: string/)
 assert.doesNotMatch(source, /columnLabels\?: Record<string, string>/)
 assert.doesNotMatch(source, /columnSettingsLabel\?: string/)
 assert.doesNotMatch(source, /总数：/)
 assert.doesNotMatch(source, /当前行数：/)
})

test('EntityListView exposes legacy CRUD page shell contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/views/EntityListView.vue'))
 assert.match(source, /interface EntityListViewProps/)
 assert.match(source, /rowKey: string/)
 assert.match(source, /title\?: string/)
 assert.match(source, /queryFields\?: ResourceCrudQueryField\[\]/)
 assert.match(source, /controller\?: ResourceCrudController/)
 assert.match(source, /const dialogOpen = ref\(false\)/)
 assert.doesNotMatch(source, /title="资源列表"/)
 assert.match(source, /const dialogMode = ref<'create' \| 'edit'>\('create'\)/)
 assert.match(source, /const isMobile = ref\(false\)/)
 assert.match(source, /const querySheetOpen = ref\(false\)/)
 assert.match(source, /const activeQueryCount = computed/)
 assert.match(source, /const activeQuerySummaries = computed/)
 assert.match(source, /const mobileQuerySummaryTitle = computed/)
 assert.match(source, /const mobileQuerySummaryText = computed/)
 assert.match(source, /const showBatchBar = computed/)
 assert.match(source, /syncViewport\(/)
 assert.match(source, /runQuery\(/)
 assert.match(source, /setControllerState/)
 assert.match(source, /props\.controller\?\.handlers\?\.query/)
 assert.match(source, /props\.controller\?\.handlers\?\.save/)
 assert.match(source, /props\.controller\?\.handlers\?\.remove/)
 assert.match(source, /props\.controller\?\.handlers\?\.actions/)
 assert.match(source, /props\.controller\?\.actions\?\.actions/)
 assert.match(source, /props\.controller\?\.state\?\.queryValues/)
 assert.match(source, /const defaultRowActions = computed<ResourceCrudRowAction\[]>\(\(\) =>/)
 assert.match(source, /dispatchAction\(/)
 assert.match(source, /resolveActionVariant\(/)
 assert.match(source, /handleFormMutation\(/)
 assert.match(source, /resetDirty\(/)
 assert.match(source, /function requestCancel\(/)
 assert.match(source, /@click="requestCancel"/)
 assert.match(source, /normalizedFormSections = computed/)
 assert.match(source, /buildCreateDraft\(/)
 assert.match(source, /buildEditDraft\(/)
 assert.match(source, /updateDraftValue\(/)
 assert.match(source, /LoadingState/)
 assert.match(source, /visibleActions/)
 assert.match(source, /visibleListActions/)
 assert.match(source, /visibleBatchActions/)
 assert.match(source, /resolvedDetailFields/)
 assert.match(source, /hasDetail = computed/)
 assert.match(source, /<template #header-actions>/)
 assert.match(source, /efs-resourcecrudpage__list-header-actions/)
 assert.match(source, /efs-resourcecrudpage__list-summary-group/)
 assert.match(source, /efs-resourcecrudpage__list-action-group/)
 assert.match(source, /<ActionBar :actions="visibleHeaderActions" align="end" :busy="resolvedBusy" \/>/)
 assert.match(source, /efs-resourcecrudpage__filter-count/)
 assert.match(source, /class="efs-resourcecrudpage__query-summary-bar"/)
 assert.match(source, /{{ activeQueryCount > 0 \? '修改' : '筛选' }}/)
 assert.match(source, /<strong>筛选条件<\/strong>/)
 assert.match(source, /应用筛选/)
 assert.match(source, /querySheetOpen = true/)
 assert.match(source, /v-if="isMobile && querySheetOpen"/)
 assert.match(source, /isMobile && showBatchBar/)
 assert.match(source, /efs-resourcecrudpage__mobile-batch-bar/)
 assert.doesNotMatch(source, /v-if="isMobile && normalizedQueryFields.length > 0" variant="ghost"/)
 assert.doesNotMatch(source, /efs-resourcecrudpage__summary-bar/)
 assert.doesNotMatch(source, /efs-resourcecrudpage__header-actions/)
 assert.doesNotMatch(source, /efs-resourcecrudpage__query-title/)
 assert.doesNotMatch(source, /efs-resourcecrudpage__query-header/)
 assert.doesNotMatch(source, /actions\.push\(\{ key: 'refresh' \}\)/)
 assert.doesNotMatch(source, /slot name="actions"/)
 assert.doesNotMatch(source, /slot name="query-fields"/)
 assert.doesNotMatch(source, /slot name="table"/)
 assert.doesNotMatch(source, /slot name="loading"/)
 assert.doesNotMatch(source, /slot name="error"/)
 assert.doesNotMatch(source, /slot name="empty"/)
 assert.doesNotMatch(source, /slot name="batch-actions"/)
 assert.doesNotMatch(source, /slot name="dialog"/)
 assert.doesNotMatch(source, /slot name="detail"/)
 assert.doesNotMatch(source, /filters\?: ResourceCrudFilterField\[\]/)
 assert.doesNotMatch(source, /filterValues\?: Record<string, string>/)
 assert.doesNotMatch(source, /selectedRowKeys\?: RowSelectionKey\[\]/)
 assert.doesNotMatch(source, /actions\?: ResourceAction\[\]/)
 assert.doesNotMatch(source, /loading\?: boolean/)
 assert.doesNotMatch(source, /error\?: boolean \| string/)
 assert.doesNotMatch(source, /subtitle\?: string/)
 assert.doesNotMatch(source, /description\?: string/)
 assert.doesNotMatch(source, /eyebrow\?: string/)
 assert.doesNotMatch(source, /statusText\?: string/)
})

test('ReportView exposes legacy report workbench contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/views/ReportView.vue'))
 assert.match(source, /defineOptions\(\{ name: 'ReportView' \}\)/)
 assert.match(source, /interface ReportViewProps/)
 assert.match(source, /title\?: string/)
 assert.match(source, /queryFields\?: ReportViewQueryField\[\]/)
 assert.match(source, /columns\?: ReportViewResultColumn\[\]/)
 assert.match(source, /controller\?: ReportViewController/)
 assert.match(source, /const localQueryValues = ref<Record<string, string>>\(\{\}\)/)
 assert.match(source, /const localPage = ref\(1\)/)
 assert.match(source, /const localPageSize = ref\(20\)/)
 assert.match(source, /runQuery\(/)
 assert.match(source, /handleSearch\(/)
 assert.match(source, /handleReset\(/)
 assert.match(source, /handlePageChange\(/)
 assert.match(source, /handlePageSizeChange\(/)
 assert.match(source, /handleExport\(/)
 assert.match(source, /props\.controller\?\.handlers\?\.query/)
 assert.match(source, /props\.controller\?\.handlers\?\.export/)
 assert.match(source, /props\.controller\?\.handlers\?\.actions/)
 assert.match(source, /props\.controller\?\.actions\?\.actions/)
 assert.match(source, /props\.controller\?\.state\?\.summary/)
 assert.match(source, /const visibleActions = computed/)
 assert.match(source, /<ReportPanel/)
 assert.match(source, /<DashboardCardPanel/)
 assert.match(source, /<DataTable/)
 assert.match(source, /<LoadingState/)
 assert.match(source, /<ErrorState/)
 assert.match(source, /<EmptyState/)
 assert.doesNotMatch(source, /slot name="query"/)
 assert.doesNotMatch(source, /slot name="result"/)
})

test('legacy report view metadata types stay key-only in the compat layer', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/legacy/report-view-types.ts'))
 assert.match(source, /export type ReportViewQueryField = \{/) 
 assert.match(source, /export type ReportViewResultColumn = \{/) 
 assert.match(source, /export type ReportViewSummaryMetric = \{/) 
 assert.match(source, /export interface ReportViewControllerState/) 
 assert.match(source, /export interface ReportViewControllerHandlers/) 
 assert.match(source, /export interface ReportViewControllerActions/) 
 assert.match(source, /export interface ReportViewController/) 
 assert.match(source, /queryValues: Record<string, string>/)
 assert.doesNotMatch(source, /label\?: string/)
 assert.doesNotMatch(source, /title\?: string/)
 assert.doesNotMatch(source, /placeholder\?: string/)
 assert.doesNotMatch(source, /i18nKey\?: string/)
})

test('resource-crud metadata types rely on key-only lookup instead of inline labels or explicit i18n keys', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/legacy/resource-crud-types.ts'))
 assert.match(source, /export type RowSelectionKey = string/)
 assert.match(source, /export type ResourceCrudColumn = \{/) 
 assert.match(source, /export type ResourceCrudQueryOption = \{/) 
 assert.match(source, /value: string/)
 assert.match(source, /export type ResourceCrudActionHandlerPayload = \{/) 
 assert.match(source, /queryValues: Record<string, string>/)
 assert.match(source, /actions\?: Record<string, ResourceCrudCustomActionHandler>/)
 assert.match(source, /key: string/)
 assert.doesNotMatch(source, /string \| number/)
 assert.doesNotMatch(source, /onClick\?: \(payload:/)
 assert.doesNotMatch(source, /onClick: \(row:/)
 assert.doesNotMatch(source, /label: string/)
 assert.doesNotMatch(source, /i18nKey\?: string/)
 assert.doesNotMatch(source, /placeholderI18nKey\?: string/)
 assert.doesNotMatch(source, /descriptionI18nKey\?: string/)
 assert.doesNotMatch(source, /hintI18nKey\?: string/)
 assert.doesNotMatch(source, /label\?: string/)
 assert.doesNotMatch(source, /title\?: string/)
 assert.doesNotMatch(source, /placeholder\?: string/)
 assert.doesNotMatch(source, /hint\?: string/)
 assert.doesNotMatch(source, /description\?: string/)
})

test('SimpleTablePanel keeps title/subtitle content props but internalizes rows label copy', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/SimpleTablePanel.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /resolvedRowsLabel = computed/)
 assert.match(source, /resolveOptionalLabel\(\{ key: 'rowsLabel'/)
 assert.doesNotMatch(source, /rowsLabel\?: string/)
 assert.match(source, /slot name="actions"/)
})

test('FormPanel exposes sectioned form, summary, and footer action contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/FormPanel.vue'))
 assert.match(source, /interface FormPanelProps/)
 assert.match(source, /sections\?: FormSection\[\]/)
 assert.match(source, /summary\?: string/)
 assert.match(source, /dirty\?: boolean/)
 assert.match(source, /footer\?: FormPanelFooter/)
 assert.match(source, /resolvedSectionsLabel = computed/)
 assert.match(source, /resolvedEmptyText = computed/)
 assert.match(source, /resolvedRequiredHint = computed/)
 assert.match(source, /resolvedFooter = computed/)
 assert.match(source, /slot name="summary"/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="footer"/)
 assert.match(source, /'submit'/)
 assert.match(source, /'cancel'/)
 assert.doesNotMatch(source, /showFooterActions\?: boolean/)
 assert.doesNotMatch(source, /sectionsLabel\?: string/)
 assert.doesNotMatch(source, /emptyText\?: string/)
 assert.doesNotMatch(source, /requiredHint\?: string/)
 assert.doesNotMatch(source, /interface FormPanelProps[\s\S]*?dirtyLabel\?: string/)
 assert.doesNotMatch(source, /interface FormPanelProps[\s\S]*?submitLabel\?: string/)
})

test('DashboardCardPanel exposes eyebrow contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/DashboardCardPanel.vue'))
 assert.match(source, /eyebrow\?: string/)
 assert.match(source, /dashboardcardpanel__value/)
})

test('DetailPanel exposes richer detail grid contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/DetailPanel.vue'))
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /description\?: string/)
 assert.match(source, /columns\?: 1 \| 2 \| 3/)
 assert.match(source, /resolvedFieldsLabel = computed/)
 assert.match(source, /resolvedEmptyText = computed/)
 assert.doesNotMatch(source, /fieldsLabel\?: string/)
 assert.doesNotMatch(source, /emptyText\?: string/)
 assert.match(source, /slot name="actions"/)
 assert.match(source, /slot name="footer"/)
})

test('MasterDetailPanel exposes split layout while internalizing default section copy', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/MasterDetailPanel.vue'))
 assert.match(source, /interface MasterDetailPanelProps/)
 assert.match(source, /splitRatio\?: string/)
 assert.match(source, /resolvedMasterTitle = computed/)
 assert.match(source, /resolvedDetailTitle = computed/)
 assert.match(source, /resolvedDetailEmptyTitle = computed/)
 assert.match(source, /resolvedDetailEmptyDescription = computed/)
 assert.doesNotMatch(source, /masterTitle\?: string/)
 assert.doesNotMatch(source, /detailTitle\?: string/)
 assert.doesNotMatch(source, /detailEmptyTitle\?: string/)
 assert.doesNotMatch(source, /detailEmptyDescription\?: string/)
 assert.match(source, /slot name="header-actions"/)
 assert.match(source, /slot name="master"/)
 assert.match(source, /name="detail"/)
})

test('CrudDialog exposes dialog mode, footer action, dirty-close guard, and close contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/CrudDialog.vue'))
 assert.match(source, /interface CrudDialogProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /summary\?: string/)
 assert.match(source, /size\?: 'sm' \| 'md' \| 'lg'/)
 assert.match(source, /closeOnBackdrop\?: boolean/)
 assert.match(source, /guardDirtyClose\?: boolean/)
 assert.match(source, /footer\?: \{/)
 assert.match(source, /resolvedFooter = computed/)
 assert.match(source, /resolvedCloseLabel = computed/)
 assert.match(source, /'update:modelValue'/)
 assert.match(source, /'submit'/)
 assert.match(source, /'cancel'/)
 assert.match(source, /'close'/)
 assert.match(source, /'request-close'/)
 assert.match(source, /const shouldGuardClose = computed/)
 assert.match(source, /emit\('request-close', \{ source \}\)/)
 assert.match(source, /emit\('cancel'\)/)
 assert.match(source, /emit\('update:modelValue', false\)/)
 assert.match(source, /slot name="header-actions"/)
 assert.match(source, /slot name="summary"/)
 assert.match(source, /slot name="footer"/)
 assert.doesNotMatch(source, /showFooterActions\?: boolean/)
 assert.doesNotMatch(source, /closeLabel\?: string/)
 assert.doesNotMatch(source, /dirtyLabel\?: string/)
 assert.doesNotMatch(source, /submitLabel\?: string/)
 assert.doesNotMatch(source, /savingLabel\?: string/)
 assert.doesNotMatch(source, /cancelLabel\?: string/)
})

test('ReportPanel exposes query/result/export contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/panels/ReportPanel.vue'))
 assert.match(source, /interface ReportPanelProps/)
 assert.match(source, /subtitle\?: string/)
 assert.match(source, /description\?: string/)
 assert.match(source, /query\?: \{/) 
 assert.match(source, /result\?: \{/) 
 assert.match(source, /resolvedQuery = computed/)
 assert.match(source, /resolvedResult = computed/)
 assert.match(source, /resolvedExportLabel = computed/)
 assert.match(source, /exportable\?: boolean/)
 assert.match(source, /resolveOptionalLabel\(\{ key: 'exportLabel'/)
 assert.match(source, /resolveOptionalLabel\(\{ key: 'queryTitle'/)
 assert.match(source, /resolveOptionalLabel\(\{ key: 'queryEmptyText'/)
 assert.match(source, /resolveOptionalLabel\(\{ key: 'resultTitle'/)
 assert.match(source, /resolveOptionalLabel\(\{ key: 'resultEmptyText'/)
 assert.match(source, /'export'/)
 assert.match(source, /slot name="query"/)
 assert.match(source, /slot name="result"/)
 assert.match(source, /slot name="header-actions"/)
 assert.match(source, /slot name="result-actions"/)
 assert.doesNotMatch(source, /queryTitle\?: string/)
 assert.doesNotMatch(source, /resultTitle\?: string/)
 assert.doesNotMatch(source, /exportLabel\?: string/)
 assert.doesNotMatch(source, /emptyText\?: string/)
})

test('ColumnSettings exposes visibleKeys show-all and reset contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/interaction/ColumnSettings.vue'))
 assert.match(source, /visibleKeys\?: string\[\]/)
 assert.match(source, /resolvedLabel = computed/)
 assert.match(source, /resolvedResetLabel = computed/)
 assert.match(source, /resolvedShowAllLabel = computed/)
 assert.doesNotMatch(source, /showAllLabel\?: string/)
 assert.doesNotMatch(source, /resetLabel\?: string/)
 assert.doesNotMatch(source, /defineProps<\{[\s\S]*label\?: string/)
 assert.match(source, /'update:visibleKeys'/)
 assert.match(source, /'show-all'/)
 assert.match(source, /'reset'/)
})

test('ActionBar exposes schema-driven action layout contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/interaction/ActionBar.vue'))
 assert.match(source, /type ActionBarItem/)
 assert.match(source, /actions\?: ActionBarItem\[\]/)
 assert.match(source, /align\?: 'start' \| 'between' \| 'end'/)
 assert.match(source, /busy\?: boolean/)
 assert.match(source, /visibleActions/)
})

test('Form and dialog shell defaults use consistent Chinese copy', () => {
 const formSource = read(path.join(repoRoot, 'packages/vue/src/panels/FormPanel.vue'))
 const dialogSource = read(path.join(repoRoot, 'packages/vue/src/panels/CrudDialog.vue'))
 const detailSource = read(path.join(repoRoot, 'packages/vue/src/panels/DetailPanel.vue'))
 const masterDetailSource = read(path.join(repoRoot, 'packages/vue/src/panels/MasterDetailPanel.vue'))
 const reportPanelSource = read(path.join(repoRoot, 'packages/vue/src/panels/ReportPanel.vue'))
 const simpleTableSource = read(path.join(repoRoot, 'packages/vue/src/panels/SimpleTablePanel.vue'))
 assert.match(formSource, /\|\| '未配置表单分组。'/)
 assert.match(formSource, /\|\| '\* 必填字段'/)
 assert.match(formSource, /\|\| '存在未保存修改'/)
 assert.match(formSource, /\|\| '保存'/)
 assert.match(formSource, /\|\| '取消'/)
 assert.match(dialogSource, /\|\| '存在未保存修改'/)
 assert.match(dialogSource, /\|\| '保存'/)
 assert.match(dialogSource, /\|\| '取消'/)
 assert.match(dialogSource, /\|\| '关闭'/)
 assert.match(detailSource, /\|\| '字段数：'/)
 assert.match(detailSource, /\|\| '暂无详情字段。'/)
 assert.match(masterDetailSource, /\|\| '主列表'/)
 assert.match(masterDetailSource, /\|\| '详情'/)
 assert.match(reportPanelSource, /\|\| '导出'/)
 assert.match(reportPanelSource, /\|\| '查询条件'/)
 assert.match(reportPanelSource, /\|\| '结果列表'/)
 assert.match(simpleTableSource, /\|\| '当前行数：'/)
})

test('LoadingState EmptyState and ErrorState expose richer state contracts', () => {
 const loadingSource = read(path.join(repoRoot, 'packages/vue/src/interaction/LoadingState.vue'))
 const emptySource = read(path.join(repoRoot, 'packages/vue/src/interaction/EmptyState.vue'))
 const errorSource = read(path.join(repoRoot, 'packages/vue/src/interaction/ErrorState.vue'))
 assert.match(loadingSource, /variant\?: 'default' \| 'resource' \| 'report'/)
 assert.match(loadingSource, /resolvedTitle = computed/)
 assert.match(loadingSource, /resolvedMessage = computed/)
 assert.doesNotMatch(loadingSource, /message\?: string/)
 assert.match(emptySource, /variant\?: 'default' \| 'resource' \| 'report'/)
 assert.match(emptySource, /resolvedIcon = computed/)
 assert.doesNotMatch(emptySource, /icon\?: string/)
 assert.match(emptySource, /slot name="actions"/)
 assert.match(errorSource, /variant\?: 'default' \| 'resource' \| 'report'/)
 assert.match(errorSource, /detail\?: string/)
 assert.match(errorSource, /resolvedIcon = computed/)
 assert.doesNotMatch(errorSource, /icon\?: string/)
 assert.match(errorSource, /slot name="actions"/)
})

test('Pagination exposes pageCount pageSizeOptions and update emits contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/interaction/Pagination.vue'))
 assert.match(source, /pageCount\?: number/)
 assert.match(source, /pageSizeOptions\?: number\[\]/)
 assert.match(source, /resolvedPageSizeLabel = computed/)
 assert.match(source, /resolvedSummaryLabel = computed/)
 assert.match(source, /resolvedPreviousLabel = computed/)
 assert.match(source, /resolvedNextLabel = computed/)
 assert.doesNotMatch(source, /pageSizeLabel\?: string/)
 assert.doesNotMatch(source, /summaryLabel\?: string/)
 assert.doesNotMatch(source, /previousLabel\?: string/)
 assert.doesNotMatch(source, /nextLabel\?: string/)
 assert.match(source, /'update:page'/)
 assert.match(source, /'update:pageSize'/)
})

test('StatusChip constrains tone variants', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/interaction/StatusChip.vue'))
 assert.doesNotMatch(source, /label\?: string/)
 assert.match(source, /<slot>—<\/slot>/)
 assert.match(source, /new Set\(\['neutral', 'success', 'warning', 'danger', 'info'\]\)/)
})

test('legacy barrel avoids exporting view-runtime controller shapes', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/legacy/index.ts'))
 assert.doesNotMatch(source, /ReportViewController/)
 assert.doesNotMatch(source, /ReportViewControllerActions/)
 assert.doesNotMatch(source, /ReportViewControllerHandlers/)
 assert.doesNotMatch(source, /ReportViewControllerState/)
 assert.doesNotMatch(source, /ResourceCrudController/)
 assert.doesNotMatch(source, /ResourceCrudControllerActions/)
 assert.doesNotMatch(source, /ResourceCrudControllerHandlers/)
 assert.doesNotMatch(source, /ResourceCrudControllerState/)
 assert.doesNotMatch(source, /ResCrudRuntimeOptions/)
 assert.doesNotMatch(source, /ResReportRuntimeOptions/)
 assert.doesNotMatch(source, /ResCrudRuntime/)
 assert.doesNotMatch(source, /ResReportRuntime/)
 assert.doesNotMatch(source, /ResRuntime/)
})

test('DataTable exposes simplified renderers visible columns row actions and row selection contract', () => {
 const source = read(path.join(repoRoot, 'packages/vue/src/interaction/DataTable.vue'))
 assert.match(source, /type CellRenderer = 'text' \| 'status' \| 'tags'/)
 assert.match(source, /formatter\?: \(value: unknown, row: Record<string, unknown>\) => unknown/)
 assert.match(source, /rowKey: string/)
 assert.match(source, /visibleColumnKeys\?: string\[\]/)
 assert.match(source, /rowActions\?: RowAction\[\]/)
 assert.match(source, /selectable\?: boolean/)
 assert.match(source, /selectedRowKeys\?: RowSelectionKey\[\]/)
 assert.match(source, /resolvedActionsLabel = computed/)
 assert.match(source, /resolvedSelectionLabel = computed/)
 assert.doesNotMatch(source, /actionsLabel\?: string/)
 assert.doesNotMatch(source, /selectionLabel\?: string/)
 assert.match(source, /visible\?: boolean/)
 assert.match(source, /inferredColumns/)
 assert.match(source, /getCurrentInstance/)
 assert.match(source, /resolveLabel/)
 assert.match(source, /resolveOptionalLabel/)
 assert.match(source, /inferRenderer/)
 assert.match(source, /resolveDisplayValue\(/)
 assert.match(source, /resolveTags\(/)
 assert.match(source, /resolveTone\(/)
 assert.match(source, /summarizeObject\(/)
 assert.match(source, /resolveRowKey/)
 assert.match(source, /'row-click'/)
 assert.match(source, /'update:selectedRowKeys'/)
 assert.match(source, /toggleSelectAll/)
 assert.match(source, /toggleRowSelection/)
 assert.match(source, /StatusChip/)
 assert.match(source, /AppTag/)
 assert.doesNotMatch(source, /columnLabels\?: Record<string, string>/)
 assert.doesNotMatch(source, /toneMap\?: Record<string, string>/)
})

