export const semanticIconMap = {
  home: '⌂',
  add: '+',
  workbench: '⌂',
  users: '◪',
  user: '👤',
  profile: '👤',
  lock: '🔒',
  password: '🔒',
  logout: '↗',
  settings: '⚙',
  filter: '⌕',
  chat: '💬',
  search: '⌖',
  refresh: '↻',
  previous: '‹',
  next: '›',
  more: '⋯',
  theme: '◐',
  light: '☼',
  dark: '☾',
  locale: '文',
  print: '🖨',
  report: '▣',
  finance: '¤',
  workflow: '⇄',
  folder: '▤',
  ban: '⊘',
  agent: '✦',
  menu: '☰',
  close: '✕',
  send: '➜',
  org: '◎',
  sessions: '☷',
} as const

export function resolveSemanticIcon(key?: string, fallback = '•') {
 if (!key) return fallback
 return semanticIconMap[key as keyof typeof semanticIconMap] || fallback
}
