export const semanticIconMap = {
  home: 'mdi-home-outline',
  add: 'mdi-plus',
  workbench: 'mdi-view-dashboard-outline',
  users: 'mdi-account-group-outline',
  user: 'mdi-account-outline',
  profile: 'mdi-account-circle-outline',
  lock: 'mdi-lock-outline',
  password: 'mdi-lock-reset',
  logout: 'mdi-logout',
  settings: 'mdi-cog-outline',
  filter: 'mdi-filter-variant',
  chat: 'mdi-chat-processing-outline',
  search: 'mdi-magnify',
  refresh: 'mdi-refresh',
  previous: 'mdi-chevron-left',
  next: 'mdi-chevron-right',
  more: 'mdi-dots-horizontal',
  theme: 'mdi-theme-light-dark',
  light: 'mdi-weather-sunny',
  dark: 'mdi-weather-night',
  locale: 'mdi-translate',
  print: 'mdi-printer-outline',
  report: 'mdi-chart-box-outline',
  finance: 'mdi-currency-usd',
  workflow: 'mdi-source-branch',
  folder: 'mdi-folder-outline',
  ban: 'mdi-cancel',
  agent: 'mdi-robot-outline',
  menu: 'mdi-menu',
  close: 'mdi-close',
  send: 'mdi-send',
  org: 'mdi-office-building-outline',
  sessions: 'mdi-history',
} as const

export function resolveSemanticIcon(key?: string, fallback = '•') {
 if (!key) return fallback
 return semanticIconMap[key as keyof typeof semanticIconMap] || fallback
}
