import {
  mdiAccountCircleOutline,
  mdiAccountGroupOutline,
  mdiAccountOutline,
  mdiCancel,
  mdiChartBoxOutline,
  mdiChatProcessingOutline,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClose,
  mdiCogOutline,
  mdiCurrencyUsd,
  mdiDotsHorizontal,
  mdiFilterVariant,
  mdiFolderOutline,
  mdiHistory,
  mdiHomeOutline,
  mdiLockOutline,
  mdiLockReset,
  mdiLogout,
  mdiMagnify,
  mdiMenu,
  mdiOfficeBuildingOutline,
  mdiPlus,
  mdiPrinterOutline,
  mdiRefresh,
  mdiRobotOutline,
  mdiSend,
  mdiSourceBranch,
  mdiThemeLightDark,
  mdiTranslate,
  mdiViewDashboardOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
} from '@mdi/js'

export const semanticIconMap = {
  home: mdiHomeOutline,
  add: mdiPlus,
  workbench: mdiViewDashboardOutline,
  users: mdiAccountGroupOutline,
  user: mdiAccountOutline,
  profile: mdiAccountCircleOutline,
  lock: mdiLockOutline,
  password: mdiLockReset,
  logout: mdiLogout,
  settings: mdiCogOutline,
  filter: mdiFilterVariant,
  chat: mdiChatProcessingOutline,
  search: mdiMagnify,
  refresh: mdiRefresh,
  previous: mdiChevronLeft,
  next: mdiChevronRight,
  more: mdiDotsHorizontal,
  theme: mdiThemeLightDark,
  light: mdiWeatherSunny,
  dark: mdiWeatherNight,
  locale: mdiTranslate,
  print: mdiPrinterOutline,
  report: mdiChartBoxOutline,
  finance: mdiCurrencyUsd,
  workflow: mdiSourceBranch,
  folder: mdiFolderOutline,
  ban: mdiCancel,
  agent: mdiRobotOutline,
  menu: mdiMenu,
  close: mdiClose,
  send: mdiSend,
  org: mdiOfficeBuildingOutline,
  sessions: mdiHistory,
} as const

export function resolveSemanticIcon(key?: string) {
 if (!key) return undefined
 return semanticIconMap[key as keyof typeof semanticIconMap]
}
